version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  build:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 2.0.2

    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
  
    working_directory: ~/repo

    steps:
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: fcrepo_wrapper
      - samvera/parallel_rspec

workflows:
  version: 2
  ci:
    jobs:
      - build:
          name: "ruby2-6"
          ruby_version: "2.6.5"
          bundler_version: '1.7'
      - build:
          name: "ruby2-5"
          ruby_version: "2.5.7"
          bundler_version: '1.7'
      - build:
          name: "ruby2-4"
          ruby_version: "2.4.9"
          bundler_version: '1.7'
